### ISSUE TITLE
Comment separator

### ISSUE THREAD

**Issue by FOAnt** [glow-labs-ltd/the-covid-memorial#33]
In the designs I did not account for a separator between the main comment from the original poster and the additional comments when in a "commenting not allowed" view. Presently they are separated by the comments box but this is insufficient in the other view.

Please may we add a horizontal rule and a title for comments as per (https://www.sketch.com/s/e0257934-06d9-4d09-8ac6-c399bdde8daa/a/WKRApg2)

**Comment by kamaldaniels** [comment]
Done in #68
